body:
  - type: textBlock
    attributes:
      name: description
      description: >
        Please provide your Radarr API key and URL
  - type: input
    attributes:
      name: url
      label: 'Radarr URL:'
      defaultValue: "http://localhost:7878/"
      description: 'Radarr server URL'
  - type: input
    attributes:
      name: api_key
      label: 'API Key:'
      defaultValue: ""
      description: 'API Key'
